version: "3.9"

services:
  tebuto-reverse-proxy:
    image: nginx:1.23.2
    container_name: "code-specialist-nginx-reverse-proxy"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled